### ISSUE TITLE
Installation of pyaudio fails

### ISSUE THREAD

**Issue by lneuhaus** [lneuhaus/pysine#2]
googling reveals the solution:

```
sudo apt-get install portaudio19-dev
```

**Comment by lneuhaus** [comment]
https://stackoverflow.com/questions/5921947/pyaudio-installation-error-command-gcc-failed-with-exit-status-1

**Comment by lneuhaus** [comment]
.. i also had to do the following to make pysine work on my ubuntu 16.04:

```
conda uninstall PortAudio
```

**Comment by rootVIII** [comment]
couldn't hurt to put that on the README for us *NIX users:)

**Comment by lneuhaus** [comment]
Thanks, done!

James <notifications@github.com> schrieb am Sa., 20. Juli 2019, 06:58:

> couldn't hurt to put that on the README for us *NIX users
