### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by TignerB** [lneuhaus/pysine#3]
FreeBSD 12.0-CURRENT, Trueos 18.03
Desktop is xfce4 4.12.4
pysine loads into python 2.7 ok, but no sound comes out of the speaker.
sine(1000.,10.) appears to work, with a proper 10S duration.
audio works with everything else, music, web, video ,etc.
It -is- working with the same os on a lenovo laptop.

**Comment by lneuhaus** [comment]
Hi, no idea what the problem is. It is likely a problem with the library underlying pysine, i.e. PyAudio. Are you able to verify that PyAudio works on your computer, e.g. by running the unit tests of PyAudio?

**Comment by lneuhaus** [comment]
closing this because it has been stale for almost a year now
